CAMERA_SOURCE = 0
PERCENTAGE_MOVEMENT = 30
MAX_SIZE_STACK_ROAD_DECISION = 7
MIDAS_DISTANCE_THRESHOLD = 130
MIDAS_MODEL = "MiDaS_small"
YOLO_MODEL = "yolov10s.pt"
RED_RATION_TRAFFIC_LIGHT = 0.1
ACTION_DECISION = {0: "no_movement", 1: "is_ok", 2: "obstacle", 3: "stop"}
